[package]
name = "possum"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bytesize = "1.3.0"
clap = { version = "4.4.2", features = ["derive"] }
libc = { git = "https://github.com/rust-lang/libc.git" }
rand = "0.8.5"
# Need sqlite3 3.42 or later.
rusqlite = { git = "https://github.com/rusqlite/rusqlite.git", features = ["bundled"] }
tempfile = "3.8.0"
log = "0.4.20"
env_logger = "0.10.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "clonefile"
harness = false
