[package]
name = "possum"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.2", features = ["derive"] }
libc = { path = "../../src/rust-libc" }
#unix = "0.6.12"
